### ISSUE TITLE
package doesn't create bitters directory on meteor 1.2.1

### ISSUE THREAD

**Issue by funkybunky** [wolvesio/meteor-bitters#2]
Hi! I suppose that package should create a bitters dir after installation, right?
Perhaps I misunderstood something, but this didn't work at my setup. I even tried downgrading fourseven:scss to 1.0.0, but that didn't help neither. I ended up manually copying the bitters stylesheet dir from the bitters repo.

**Comment by aleatorik** [comment]
Being that it is a meteor package, as stated in the readme the folder is installed to ".meteor/local/build/programs/server/assets/packages/wolves_bitters"

Also it is noted that it only does so after the first restart of the meteor application. Please let me know if this helps you. Also take a look at the documentation in the read me that describes this. Cheers

**Comment by funkybunky** [comment]
Thank you for your kind response! I'm pretty new to Meteor and was a bit confused. Things are working well now, although I'm not using this package anymore.
Anyway, keep up the good work :)
