### ISSUE TITLE
Update to latest to avoid box-sizing deprecation warnings

### ISSUE THREAD

**Issue by mcrider** [wolvesio/meteor-bitters#3]
Hiya, getting a ton of deprecation warnings in my meteor log:

```
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	 .meteor/local/build/programs/server/assets/packages/wolves_bourbon/bourbon/bourbon-deprecated-upcoming:410, in mixin `box-sizing`
	 .meteor/local/build/programs/server/assets/packages/wolves_bitters/bitters/forms:30
```

Can we update to the latest bitters styles that removes the use of the box-sizing mixin?  I'd submit a PR but i'm not sure where the /bitters/extends/ directory is coming from (is that refills?)

Thanks!

**Comment by aleatorik** [comment]
I will update this, this evening. Thank you for letting me know

**Comment by aleatorik** [comment]
These have been updated as of this commit - https://github.com/wolvesio/meteor-bitters/commit/e6aa6bd6512aeb3d488036a9e1b182365000fd02 

Updating your package to 2.1.0 (newest) should address anyissues and also get you v1 bitters
