### ISSUE TITLE
".meteor/local/build/programs/server/assets/packages/wolves_bitters" not created

### ISSUE THREAD

**Issue by holmrenser** [wolvesio/meteor-bitters#5]
I tried to install meteor-bitters like so:
`meteor add wolves-bitters`

I then wanted to proceed with the following:

> If you want to use Neat functions in Bitters, you can `@import "grid-settings";` before Neat, remove `@import "grid-settings";` from .meteor/local/build/programs/server/assets/packages/wolves_bitters/bitters/_base.scss

However this file does not exist in my project...

Any idea what is going on?

**Comment by wolves** [comment]
Have you installed the neat package that I have published as well?

**Comment by deuceBag33** [comment]
all three packages installed, Meteor 1.4, no packages folder @ .meteor/local/build/programs/server/assets/

restarted several times

**Comment by wolves** [comment]
## This package is no longer maintained since the progression of Meteor to the use of NPM allows for thoughtbot's main package to be leveraged

[https://github.com/thoughtbot/bitters#installation](https://github.com/thoughtbot/bitters#installation)
